@echo off
color 0C

start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_newlaugh.ogg"
timeout /t 2 /nobreak >nul
echo Flowey: You think you can run ?

timeout /t 5 /nobreak >nul
echo Flowey: I know where you live...
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"

echo Flowey: Flowey: Don't waste your time... You made a mistake by provoking me >:(. But don't worry...
timeout /t 7 /nobreak >nul

start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_phase2_yarn.ogg"
start "" "%~dp0Timer.bat"
start "" "%~dp0icones.vbs"
start "" "%~dp0fond d'ecrand.vbs"
start "" /min "%~dp0Photo.bat"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"

start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"
start "" "C:\Program Files\VideoLAN\VLC\vlc.exe" --intf dummy --play-and-exit "%~dp0Song\f_laugh.ogg"


@echo off
setlocal EnableDelayedExpansion

set /a choix=%random% %% 4 + 1

if %choix%==1 start "" calc.exe
if %choix%==2 start "" notepad.exe
if %choix%==3 start "" cmd.exe
if %choix%==4 start "" explorer.exe

@echo off
setlocal EnableDelayedExpansion
title SYSTEM ERROR
mode con: cols=100 lines=30
color 0C

start "" "%~dp0Scan.bat"

timeout /t 2 /nobreak >nul
start "" "%~dp0Bureau.bat"
exit
exit
echo.
set /p "=You can't escape... I am God :)))) ! ! !"
pause >nul
